### PR TITLE
Pep8 compliance

### PR DESCRIPTION
**Pull request by holtchesley**
This branch passes pylint's basic pep8 compliance (default configuration) with few meaningful changes to code.

The only meaningful change is the use of `isinstance` instead of `type` in node.py. 

Otherwise, whitespace has been normalized, unused imports have been dropped, meaningless constructors have been removed, and docstrings have been added.

In some places, it made sense to exclude a class or method from pylints checks for the time. By default pylint warns against classes that have more than 7 attributes, or less than 2 public methods, and in one case, pylint warned against a function requiring self as a first parameter, but not using it.
All overrides appear the line above their application as 
`# pylint: disable=name-of-warning`

### CODE REVIEW

**Comment by holtchesley** [comment]
This addresses issue #19 .

**Comment by danluu** [comment]
This is awesome! Just out of curiosity, what rule violation caused the following change?

~~~
 class HealNetwork(NetworkEvent):
-    def __init__(self,event_map): super().__init__(event_map)
-    def handle(self,nodes,network_broker):
-        network_broker['connections'] = set([(f,t) for f in self.node_ids for t in self.node_ids if t != f])
-        network_broker['delays'] = {(f,t):0 for f in self.node_ids for t in self.node_ids if t != f}
-        network_broker['duplicates'] = {(f,t):0 for f in self.node_ids for t in self.node_ids if t != f}
+    "Backs out all Network events"
+    def handle(self, nodes, network_broker):
+        node_ids = nodes.keys()
+        network_broker['connections'] = set(
+            [(f, t) for f in node_ids for t in node_ids if t != f])
+        network_broker['delays'] = {
+            (f, t): 0 for f in node_ids for t in node_ids if t != f}
+        network_broker['duplicates'] = {
+            (f, t): 0 for f in node_ids for t in node_ids if t != f}
~~~

**Comment by holtchesley** [comment]
This is a combination of the class missing a docstring ("Backs out all Network Events"), a pep8 guideline against constructors that only delegate to super,  and a line length issue for each of the `network_broker...` lines.

**Comment by ghost** [comment]
Can we rename `DeliveryDrop` to `SendDrop` since there is another class called `ReceiveDrop`?

**Pull request merged**
